name: Debian packages

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-debs:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        name: [
          x64_buster,
          x64_bullseye,
          x64_bookworm
        ]

        include:
          - name: x64_buster
            dist: buster

          - name: x64_bullseye
            dist: bullseye

          - name: x64_bookworm
            dist: bookworm

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch debian files
        run: |
          wget https://launchpad.net/~nerdboy/+archive/ubuntu/embedded/+sourcefiles/libtins/4.2-1build3ci/libtins_4.2-1build3ci.debian.tar.xz
          tar xf libtins_4.2*.tar.xz && rm *debian.tar.xz
          ls

      - name: Build deb packages
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          before-build-hook: |
            ver=$(git describe --tags | sed -e "s|v||" | cut -d- -f1)
            rev=$(git describe --tags | sed -e "s|v||" | cut -d- -f2)
            hash=$(git rev-parse HEAD)
            sed -i -e "s|libtins4.2|libtins$ver|g" debian/control
            dch --maintmaint --newversion "$ver-1buildci$rev" "Version $ver-1buildci$rev"
            dch --maintmaint --release ""
          docker-image: "debian:${{ matrix.dist }}-slim"
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: devscripts git cmake

      - name: Upload deb files
        uses: actions/upload-artifact@v3
        with:
          name: "deb-packages"
          path: ./debian/artifacts/*.deb
