name: Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Ubuntu-Tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: sudo apt-get install -y libpcap-dev libssl-dev libgtest-dev

      - name: Add python requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run build
        run: |
          tox -e tools

      - name: Run tests
        run: |
          tox -e tests
