name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Ubuntu-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install libpcap
        run: sudo apt-get install -y libpcap-dev

      - name: Initialize build system
        run: mkdir build && cd build && cmake ..

      - name: Build tests
        run: cmake --build build --target tests

      - name: Run tests
        run: ctest build
